###  Registrar un nuevo usuario
POST http://localhost:8080/api/usuarios/registrar
Content-Type: application/json

{
  "nombre": "Sara",
  "correo": "sara@mail.com",
  "contrasena": "12234",
  "cedula": "102203040",
  "activo": true
}

###  Registrar otro usuario
POST http://localhost:8080/api/usuarios/registrar
Content-Type: application/json

{
  "nombre": "María Gómez",
  "correo": "maria@mail.com",
  "contrasena": "abcd",
  "cedula": "555888999",
  "activo": true
}

###  Iniciar sesión (usuario existente)
POST http://localhost:8080/api/usuarios/login?correo=j@mail.com&contrasena=1234


###  Cerrar sesión
POST http://localhost:8080/api/usuarios/logout?correo=juan@mail.com

### Cambiar contraseña
PUT http://localhost:8080/api/usuarios/9/cambiarContrasena?contrasenaActual=1234&nuevaContrasena=5678

### Listar todos los usuarios
GET http://localhost:8080/api/usuarios

###

### Buscar usuario por ID
GET http://localhost:8080/api/usuarios/12

### Eliminar usuario
DELETE http://localhost:8080/api/usuarios/9


### Registrar nueva venta
POST http://localhost:8080/api/ventas/registrar
Content-Type: application/json

{
  "estado": "Pendiente",
  "ingresoTotal": 120000,
  "fechaVenta": "2025-10-19",
  "pedido": {
    "idPedido": 1
  },
  "proveedor": {
    "idProveedor": 2
  }
}

### Consultar todas las ventas
GET http://localhost:8080/api/ventas/consultar


###  Buscar venta por ID
GET http://localhost:8080/api/ventas/1

###  Actualizar estado de una venta
PUT http://localhost:8080/api/ventas/1/estado?nuevoEstado=Entregado


### Actualizar proveedor de una venta
PUT http://localhost:8080/api/ventas/1/proveedor?idProveedor=3

### Eliminar venta
DELETE http://localhost:8080/api/ventas/6

### Crear nuevo pedido
POST http://localhost:8080/api/pedidos
Content-Type: application/json

{
  "usuario": { "idUsuario": 9},
  "observacion": "Pedido inicial",
  "fecha": "2025-10-19T10:00:00"
}

###  Listar todos los pedidos
GET http://localhost:8080/api/pedidos


###  Buscar pedido por ID
GET http://localhost:8080/api/pedidos/1


### Calcular total de pedido
GET http://localhost:8080/api/pedidos/1/total

###  Actualizar estado del pedido
PUT http://localhost:8080/api/pedidos/1/estado?nuevoEstado=Enviado

###  Cancelar pedido
PUT http://localhost:8080/api/pedidos/1/cancelar

###  Eliminar pedido
DELETE http://localhost:8080/api/pedidos/12
### Crear una nueva notificación
POST http://localhost:8080/api/notificaciones
Content-Type: application/json

{
  "mensaje": "Tu pedido ha sido despachado.",
  "estado": "No leída",
  "usuario": { "idUsuario": 12 }
}

### Listar todas las notificaciones
GET http://localhost:8080/api/notificaciones
### Buscar notificación por ID
GET http://localhost:8080/api/notificaciones/12

### Enviar notificación genérica
POST http://localhost:8080/api/notificaciones/enviar?mensaje=Tu%20pedido%20est%C3%A1%20en%20camino
Content-Type: application/json

{
  "idUsuario": 12,
  "nombre": "Juan Pérez"
}
### Notificar cambio en pedido
POST http://localhost:8080/api/notificaciones/pedido?estado=Entregado
Content-Type: application/json

{
  "idUsuario": 12,
  "nombre": "Juan Pérez"
}


###  Notificar promoción
POST http://localhost:8080/api/notificaciones/promocion?descripcion=Descuento%20del%2050%25%20en%20vinilos
Content-Type: application/json

{
  "idUsuario": 1,
  "nombre": "María Gómez"
}


###  Simular envío de correo
POST http://localhost:8080/api/notificaciones/correo?email=cliente@mail.com&asunto=Oferta&mensaje=Promoci%C3%B3n%20disponible
